---
- hosts: localhost
  vars:
   host: "10.172.10.1"
   username: "userxx"
   vdom: "root"
   ssl_verify: "False"
  vars_prompt:
  - name: password
    prompt: "Type the password of your fortigate admin account"
    private: no.
  tasks:
  - name: Configure firewall interface switch -> vlan_101
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_policy:
        action: "accept"
        name: "switch to vlan_101"
        srcintf: 
         - 
           name: "switch"
        dstintf: 
         - 
           name: "vlan_101"
        srcaddr: 
         - 
           name: "switch address"
        dstaddr: 
         - 
           name: "vlan_101 address"
        schedule: "always"
        service: 
         - 
           name: "HTTP"
         -
           name: "SSH"
        fsso: "disable"
        status: enable
        policyid: 5
  - name: Configure firewall interface vlan_101 -> switch
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_policy:
        action: "accept"
        name: "vlan_101 to switch"
        srcintf: 
         - 
           name: "vlan_101"
        dstintf: 
         - 
           name: "switch"
        srcaddr: 
         - 
           name: "vlan_101 address"
        dstaddr: 
         - 
           name: "switch address"
        schedule: "always"
        service: 
         - 
           name: "ALL"
        fsso: "disable"
        status: enable
        policyid: 6
  - name: Configure firewall interface vlan_101 -> wan1
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_policy:
        action: "accept"
        name: "vlan_101 to wan1"
        srcintf: 
         - 
           name: "vlan_101"
        dstintf: 
         - 
           name: "wan1"
        srcaddr: 
         - 
           name: "vlan_101 address"
        dstaddr: 
         - 
           name: "all"
        schedule: "always"
        service: 
         - 
           name: "HTTP"
         -
           name: "HTTPS"
         - 
           name: "DNS"
         - 
           name: "SSH"
         - 
           name: "ALL_ICMP"
        fsso: "disable"
        status: enable
        policyid: 7
